root: true

env:
  es2023: true
  browser: true

rules:
  '@typescript-eslint/space-before-function-paren': 'off'

parser: '@typescript-eslint/parser'

parserOptions:
  project: tsconfig.json
  sourceType: module

plugins:
  - '@typescript-eslint'

extends:
  - eslint:recommended
  - standard
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
  - plugin:astro/recommended
  - prettier

overrides:
  - files: '*.astro'
    parser: astro-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions: .astro

ignorePatterns: ['dist', 'build', 'node_modules']
